// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCxEDL0IhXgFZDGSvtC_GICQDFcwzUFF0s',
    appId: '1:722452556351:android:bbc156ad0601261a97e68a',
    messagingSenderId: '722452556351',
    projectId: 'mentor-mind-aa765',
    storageBucket: 'mentor-mind-aa765.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB9xmghvdBhWrKRzEDnGiu7vyPvuHWIS10',
    appId: '1:722452556351:ios:a3b947b673f29cf997e68a',
    messagingSenderId: '722452556351',
    projectId: 'mentor-mind-aa765',
    storageBucket: 'mentor-mind-aa765.firebasestorage.app',
    iosClientId: '722452556351-clb5opngp2jgp0jko6hophqja9tp38en.apps.googleusercontent.com',
    iosBundleId: 'com.mentorminds.mentorMinds',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB9xmghvdBhWrKRzEDnGiu7vyPvuHWIS10',
    appId: '1:722452556351:ios:823964b9f46ebc2f97e68a',
    messagingSenderId: '722452556351',
    projectId: 'mentor-mind-aa765',
    storageBucket: 'mentor-mind-aa765.firebasestorage.app',
    iosBundleId: 'com.arnobrizwan.mentorminds',
  );

}